### ISSUE TITLE
Create MobileObject project for serialization

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/Ystari#6]
This could be a separate project under the Ystari solution for now, or a separate solution altogether, but either way the serialization code should not be within Ystari directly.

This project would basically contain the MobileFormatter code from CSLA cleaned up and scrubbed for modern consumption. It would also have the ability to use DI for ctor injection during deserialization.

**Comment by rockfordlhotka** [comment]
I have created a repo for the serializer project: https://github.com/MarimerLLC/MobileObject

**Comment by JasonBock** [comment]
No more work is going into Ystari.
